
button_address = {
    'B1': ['A01', 'A02'],
    'B2': ['A03', 'A04']}

motion_detect_address = {
    'D1': ['A01', 'A02'],
    'D2': ['A03', 'A04']}

# places_name = {
#     "Garde-Robe": 0,
#     "Entrée près de la porte": 0,
#     "Entrée vers le salon": 0,
#     "Corridor face à cuisine": 0,
#     "Corridor face à placard sono": 0,
#     "Salon": 0,
#     "Lampe droite": 0,
#     "Lampe gauche": 0,
#     "Sous le comptoir téléphone": 0,
#     "Sous le comptoir lavabos": 0,
#     "Ilôt central": 0,
#     "Au dessu du lavabo": 0,
#     "A côté du lavabo": 0,
#     "Côté frigidaire": 0,
#     "Côté salle à manger": 0,
#     "Au-dessus de la table": 0,
#     "Près de la fenêtre": 0,
#     "Fond": 0,
#     "Lavabo": 0,
#     "Corridor statue": 0,
#     "Corridor salle de bain": 0,
#     "Murale bibliothèque vers sous-sol": 0,
#     "Corridor bibliothèque vers sous-sol": 0,
#     "Placard sono": 0,
#     "Au-dessus de la TV": 0,
#     "Au centre": 0,
#     "Au-dessus du lit 1": 0,
#     "Grand garde-robe": 0,
#     "Petit garde-robe": 0,
#     "Marches 1": 0,
#     "Marches 2": 0,
#     "Au-dessus du lit": 0,
#     "Au-dessus du bureau": 0,
#     "Garde-Robe 1": 0,
#     "Entrée": 0,
#     "Garde-Robe 2": 0,
#     "Garde-Linge 3": 0,
#     "Plafond 1": 0,
#     "Comptoir 1": 0,
#     "Statue": 0,
#     "Mural Entrée chambre": 0,
#     "Douche": 0,
#     "Toilette": 0,
#     "Comptoir": 0,
#     "Face à la fenêtre": 0,
#     "Au-dessus du lit 2": 0,
#     "Prises près du lit": 0,
#     "Garde-Robe 3": 0,
#     "Garde-Linge": 0,
#     "Marches": 0,
#     "Plafond": 0,
#     "Centre": 0,
#     "Près du mur": 0,
#     "Encastrés": 0,
#     "Près du panneau électrique": 0,
#     "Salle du frigidaire": 0,
#     "Salle principale": 0,
#     "Salle géothermie": 0,
#     "Salle sous cuisine": 0,
#     "Salle hydrogène": 0,
#     "Entrée principale 1": 0,
#     "Entrée principale 2": 0,
#     "Entrée près du cabanon": 0,
#     "Entrée près du BBQ": 0,
#     "Façade arrière": 0,
#     "Terrain" : 0,
#
# }

macros_names = {'nameone': [0,'Garde-Robe','Entrée près de la porte','Entrée vers le salon'],
                }

places_name = {
    'Garde-Robe': [0, 'A01', 'A02'],
    'Entrée près de la porte': [0, 'A01', 'A02'],
    'Entrée vers le salon': [0, 'A01', 'A02'],
    'Corridor face à cuisine': [0, 'A01', 'A02'],
    'Corridor face à placard sono': [0, 'A01', 'A02'],
    'Salon': [0, 'A01', 'A02'],
    'Lampe droite': [0, 'A01', 'A02'],
    'Lampe gauche': [0, 'A01', 'A02'],
    'Sous le comptoir téléphone': [0, 'A01', 'A02'],
    'Sous le comptoir lavabos': [0, 'A01', 'A02'],
    'Ilôt central': [0, 'A01', 'A02'],
    'Au dessu du lavabo': [0, 'A01', 'A02'],
    'A côté du lavabo': [0, 'A01', 'A02'],
    'Côté frigidaire': [0, 'A01', 'A02'],
    'Côté salle à manger': [0, 'A01', 'A02'],
    'Au-dessus de la table': [0, 'A01', 'A02'],
    'Près de la fenêtre': [0, 'A01', 'A02'],
    'Fond': [0, 'A01', 'A02'],
    'Lavabo': [0, 'A01', 'A02'],
    'Corridor statue': [0, 'A01', 'A02'],
    'Corridor salle de bain': [0, 'A01', 'A02'],
    'Murale bibliothèque vers sous-sol': [0, 'A01', 'A02'],
    'Corridor bibliothèque vers sous-sol': [0, 'A01', 'A02'],
    'Placard sono': [0, 'A01', 'A02'],
    'Au-dessus de la TV': [0, 'A01', 'A02'],
    'Au centre': [0, 'A01', 'A02'],
    'Au-dessus du lit 1': [0, 'A01', 'A02'],
    'Grand garde-robe': [0, 'A01', 'A02'],
    'Petit garde-robe': [0, 'A01', 'A02'],
    'Marches 1': [0, 'A01', 'A02'],
    'Marches 2': [0, 'A01', 'A02'],
    'Au-dessus du lit': [0, 'A01', 'A02'],
    'Au-dessus du bureau': [0, 'A01', 'A02'],
    'Garde-Robe 1': [0, 'A01', 'A02'],
    'Entrée': [0, 'A01', 'A02'],
    'Garde-Robe 2': [0, 'A01', 'A02'],
    'Garde-Linge 3': [0, 'A01', 'A02'],
    'Plafond 1': [0, 'A01', 'A02'],
    'Comptoir 1': [0, 'A01', 'A02'],
    'Statue': [0, 'A01', 'A02'],
    'Mural Entrée chambre': [0, 'A01', 'A02'],
    'Douche': [0, 'A01', 'A02'],
    'Toilette': [0, 'A01', 'A02'],
    'Comptoir': [0, 'A01', 'A02'],
    'Face à la fenêtre': [0, 'A01', 'A02'],
    'Au-dessus du lit 2': [0, 'A01', 'A02'],
    'Prises près du lit': [0, 'A01', 'A02'],
    'Garde-Robe 3': [0, 'A01', 'A02'],
    'Garde-Linge': [0, 'A01', 'A02'],
    'Marches': [0, 'A01', 'A02'],
    'Plafond': [0, 'A01', 'A02'],
    'Centre': [0, 'A01', 'A02'],
    'Près du mur': [0, 'A01', 'A02'],
    'Encastrés': [0, 'A01', 'A02'],
    'Près du panneau électrique': [0, 'A01', 'A02'],
    'Salle du frigidaire': [0, 'A01', 'A02'],
    'Salle principale': [0, 'A01', 'A02'],
    'Salle géothermie': [0, 'A01', 'A02'],
    'Salle sous cuisine': [0, 'A01', 'A02'],
    'Salle hydrogène': [0, 'A01', 'A02'],
    'Entrée principale 1': [0, 'A01', 'A02'],
    'Entrée principale 2': [0, 'A01', 'A02'],
    'Entrée près du cabanon': [0, 'A01', 'A02'],
    'Entrée près du BBQ': [0, 'A01', 'A02'],
    'Façade arrière': [0, 'A01', 'A02'],
    'Terrain' :[0, 'A01', 'A02']
}

button_all_addresses = {
    "B1",
    "B2",
    "B3",
    "B4",
    "B5",
    "B6",
    "B7",
    "B8",
    "B9",
    "B10",
    "B11",
    "B12",
    "B13",
    "B14",
    "B15",
    "B16",
    "B17",
    "B18",
    "B19",
    "B20",
    "B21",
    "B22",
    "B23",
    "B24",
    "B25",
    "B26",
    "B27",
    "B28",
    "B29",
    "B30",
    "B31",
    "B32",
    "B33",
    "B34",
    "B35",
    "B36",
    "B37",
    "B38",
    "B39",
    "B40",
    "B41",
    "B42",
    "B43",
    "B44",
    "B45",
    "B46",
    "B47",
    "B48",
    "B49",
    "B50",
    "B51",
    "B52",
    "B53",
    "B54",
    "B55",
    "B56",
    "B57",
    "B58",
    "B59",
    "B60",
    "B61",
    "B62",
    "B63",
    "B64",
    "B65",
    "B66",
}